name = "nekonymous"
main = "src/index.ts"
compatibility_date = "2026-06-15"

workers_dev = true

kv_namespaces = [
  { binding = "NekonymousKV", id = "de26a1b398614383a2b9702fafaa8824" },
]

[placement]
mode = "smart"

[vars]
PUBLIC_SITE_URL = "https://nekonymous.mohetios.dev"

[[routes]]
pattern = "nekonymous.mohetios.dev"
custom_domain = true

[durable_objects]
bindings = [{ name = "INBOX_DO", class_name = "InboxSqliteDurableObject" }]

[[migrations]]
tag = "v1"
new_classes = ["InboxDurableObject"]

[[migrations]]
tag = "v2-delete-inbox"
deleted_classes = ["InboxDurableObject"]

[[migrations]]
tag = "v3-inbox-sqlite"
new_sqlite_classes = ["InboxSqliteDurableObject"]
