export const SETTINGS_CALLBACK = {
  home: "st:home",
  editName: "st:en",
  pause: "st:pause",
  resume: "st:resume",
  clearBlocks: "st:cb",
  resetMatch: "st:rm",
  about: "st:about",
  stats: "st:stats",
  clearData: "st:cd",
  confirmClearData: "st:yd",
  confirmClearBlocks: "st:yb",
  confirmResetMatch: "st:yr",
  cancel: "st:n",
} as const;
