/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.types.jsonc --include-runtime=false --env-interface=CloudflareEnv src/worker-configuration.d.ts` (hash: f43ead316164bd7919c4de181e29de10)
interface __BaseEnv_CloudflareEnv {
	NEKO_KV: KVNamespace;
	DB: D1Database;
	CONVERSATION_VECTORS: VectorizeIndex;
	NEKO_OUTBOX_QUEUE: Queue;
	NEKO_STATS_QUEUE: Queue;
	NEKO_PROFILE_INDEX_QUEUE: Queue;
	SECRET_TELEGRAM_API_TOKEN: string;
	BOT_SECRET_KEY: string;
	APP_MASTER_KEY: string;
	APP_HMAC_PEPPER: string;
	BOT_INFO: string;
	BOT_NAME: string;
	BOT_USERNAME: string;
	USER_STATE_DO: DurableObjectNamespace<import("./index").UserStateDurableObject>;
	TELEGRAM_OUTBOX_DO: DurableObjectNamespace<import("./index").TelegramOutboxDurableObject>;
	TICKET_VAULT: DurableObjectNamespace<import("./index").TicketVaultDurableObject>;
	SAFETY_STATE_DO: DurableObjectNamespace<import("./index").SafetyStateDurableObject>;
	PROFILE_VAULT_DO: DurableObjectNamespace<import("./index").ProfileVaultShardDurableObject>;
	CONVERSATION_VAULT_DO: DurableObjectNamespace<import("./index").ConversationVaultShardDurableObject>;
	PAIR_LEDGER_DO: DurableObjectNamespace<import("./index").PairLedgerShardDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "UserStateDurableObject" | "TelegramOutboxDurableObject" | "TicketVaultDurableObject" | "SafetyStateDurableObject" | "ProfileVaultShardDurableObject" | "ConversationVaultShardDurableObject" | "PairLedgerShardDurableObject";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
