/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.types.jsonc --include-runtime=false --env-interface=CloudflareEnv src/worker-configuration.d.ts` (hash: 5d79f5f9aeee65a5577bc99895263959)
interface __BaseEnv_CloudflareEnv {
	NEKO_KV: KVNamespace;
	DB: D1Database;
	CONVERSATION_VECTORS: VectorizeIndex;
	NEKO_OUTBOX_QUEUE: Queue;
	NEKO_STATS_QUEUE: Queue;
	NEKO_PROFILE_INDEX_QUEUE: Queue;
	SECRET_TELEGRAM_API_TOKEN: string;
	BOT_SECRET_KEY: string;
	APP_MASTER_KEY: string;
	APP_HMAC_PEPPER: string;
	BOT_INFO: string;
	BOT_NAME: string;
	BOT_USERNAME: string;
	USER_STATE_DO: DurableObjectNamespace<import("./index").UserStateDurableObjectV4>;
	TELEGRAM_OUTBOX_DO: DurableObjectNamespace<import("./index").TelegramOutboxDurableObjectV4>;
	TICKET_VAULT: DurableObjectNamespace<import("./index").TicketVaultDurableObjectV4>;
	SAFETY_STATE_DO: DurableObjectNamespace<import("./index").SafetyStateDurableObjectV4>;
	PROFILE_VAULT_DO: DurableObjectNamespace<import("./index").ProfileVaultShardDurableObjectV2>;
	CONVERSATION_VAULT_DO: DurableObjectNamespace<import("./index").ConversationVaultShardDurableObjectV2>;
	PAIR_LEDGER_DO: DurableObjectNamespace<import("./index").PairLedgerShardDurableObjectV2>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "UserStateDurableObjectV4" | "TelegramOutboxDurableObjectV4" | "TicketVaultDurableObjectV4" | "SafetyStateDurableObjectV4" | "ProfileVaultShardDurableObjectV2" | "ConversationVaultShardDurableObjectV2" | "PairLedgerShardDurableObjectV2";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
